server:
  port: 6666
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/back_manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456
  
